<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BankATMSimulator</RootNamespace>
    <AssemblyName>BankATMSimulator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Make sure the Data folder + seed file get copied next to the built exe -->
    <None Update="Data\accounts.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
